schema_version: 1

context:
  name: katago
  version: "1.16.0"
  build_number: 1
  string_prefix: ${{ "bla" }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # NOTE: The below block using git as a source is disabled for now, see `source.patches` section.
  # use git_url, because katago needs a git repo to compile BUILD_DISTRIBUTED support;
  # this cannot (or rather: should not) be patch out, or even patched at all (-> dirty tag),
  # compare the exceedingly clear instructions/pleas here:
  # https://github.com/lightvector/KataGo/blob/master/Compiling.md#building-for-distributed
  git: https://github.com/lightvector/KataGo.git
  tag: v${{ version }}

build:
  number: ${{ build_number }}
  skip:
    - not win
  string: ${{ string_prefix }}h${{ hash }}_${{ build_number }}

about:
  summary: GTP engine and self-play learning in Go
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/lightvector/KataGo

extra:
  recipe-maintainers:
    - hadim
