schema_version: 1

context:
  name: katago
  version: "1.16.2"
  build_number: 1
  cuda: ${{ true if cuda_compiler_version != "None" else false }}
  cuda_build_string: cuda_${{ cuda_compiler_version | version_to_buildstring }}
  string_prefix: ${{ cuda_build_string if cuda else "cpu_" }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # NOTE: Use git as source because katago needs a git repo to compile BUILD_DISTRIBUTED support;
  # this cannot (or rather: should not) be patch out, or even patched at all (-> dirty tag),
  # compare the exceedingly clear instructions/pleas here:
  # https://github.com/lightvector/KataGo/blob/master/Compiling.md#building-for-distributed
  git: https://github.com/lightvector/KataGo.git
  tag: v${{ version }}

build:
  number: ${{ build_number }}
  skip:
    - cuda and match(cuda_compiler_version, "<12")
  string: ${{ string_prefix }}h${{ hash }}_${{ build_number }}
  variant:
    use_keys:
      # use cuda from the variant config, e.g. to build multiple CUDA variants
      - ${{ "cuda" if cuda else "cpu" }}
    # this will down-prioritize the cuda variant versus other variants of the package
    down_prioritize_variant: ${{ 1 if cuda else 0 }}

requirements:
  build:
    - if: cuda
      then:
        - ${{ compiler('cuda') }}

    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - curl
    - git
  host:
    - if: cuda
      then:
        - cuda-version ==${{ cuda_compiler_version }}
        - libcublas-dev
        - cudnn
        - ${{ "nccl" if linux }}

    # libraries
    - zlib
    - libzip
    - eigen
    # necessary for BUILD_DISTRIBUTED
    - openssl

tests:
  - files:
      source:
        - cpp/tests/
    script:
      - katago
      - katago version

      # fails some accuracy tests on osx
      - ${{ "katago runtests" if not osx }}

      # disable failing tests on osx, linux-64-cpu
      # - ${{ "katago runnnlayertests" if not cuda }}

      # run some tests that hopefully exercise the distributed code a bit as well
      # (based on searching "distributed" under cpp/tests and running the right portion)

      - if: unix
        then:
          - cd cpp/
          - mkdir tests/scratch
          - katago runoutputtests
          - ${{ "katago runtinynntests tests/scratch 1.0" if not cuda }}

      - if: win
        then:
          - cd cpp/
          - mkdir tests\scratch
          - ${{ "katago runtinynntests tests/scratch 1.0" if not cuda }}

about:
  summary: GTP engine and self-play learning in Go
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/lightvector/KataGo

extra:
  recipe-maintainers:
    - hadim
