# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

[project]
name = "katago-feedstock"
version = "3.45.3"
description = "Pixi configuration for conda-forge/katago-feedstock"
authors = ["@conda-forge/katago"]
channels = ["conda-forge"]
platforms = ['linux-64', 'osx-64', 'win-64']

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
inspect-all = "inspect_artifacts --all-packages"
build = "rattler-build build --recipe recipe"

[feature.smithy.dependencies]
conda-smithy = "*"

[feature.smithy.tasks]
build-locally = "python ./build-locally.py"
smithy = "conda-smithy"
rerender = "conda-smithy rerender"
lint = "conda-smithy lint recipe"

[environments]
smithy = ["smithy"]